#all: pract4a.exe pract4b.exe pract4c.exe
      
#pract4a.exe: pract4a.obj
#	tlink /t pract4a

#pract4a.obj: pract4a.asm
#	tasm /zi pract4a.asm

pract4b.exe: pract4b.obj
	tlink /v pract4b

pract4b.obj: pract4b.asm
	tasm /zi pract4b.asm

#pract4c.exe: pract4c.obj
#	tlink /v pract4c

#pract4c.obj: pract4c.asm
#	tasm /zi pract4c.asm